name: Process Issue Form Submission

on:
  issues:
    types: [opened, edited]

jobs:
  generate_json:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'add-project')
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main # Ensure the main branch is checked out

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install JSON Schema Validator and Formats
        run: |
          npm install -g ajv-cli ajv-formats

      - name: Extract Issue Form Data and Generate JSON
        id: generate_json
        run: |
          # Save the issue body to a file
          echo "${{ github.event.issue.body }}" > issue_body.md

          # Run the external script to process the issue and generate JSON
          node scripts/process-issue.js issue_body.md

      - name: Validate JSON File
        run: |
          # Ensure the schema.json file is in the correct path
          ajv -c ajv-formats validate -s schema.json -d "data/projects/${{ steps.generate_json.outputs.slug }}.json" --strict=false

      - name: Create a New Branch and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          BRANCH_NAME="add-${{ steps.generate_json.outputs.slug }}"

          git fetch origin

          git stash --include-untracked


          if git rev-parse --verify "${BRANCH_NAME}"; then
            git checkout "${BRANCH_NAME}"
          else
            git checkout -b "${BRANCH_NAME}"
          fi

          git pull --ff-only origin "${BRANCH_NAME}"

          git stash pop || true
          
          git add "data/projects/${{ steps.generate_json.outputs.slug }}.json"
          
          git commit -m "Update project: ${{ steps.generate_json.outputs.slug }}"
          git push origin "${BRANCH_NAME}"
          
      - name: Install GitHub CLI
        run: |
          sudo apt-get install -y gh

      - name: Create Pull Request
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_TITLE="Add new project: ${{ steps.generate_json.outputs.slug }}"
          PR_BODY="This PR adds or updates the project file for the project slug ${{ steps.generate_json.outputs.slug }}."
          BRANCH_NAME="add-${{ steps.generate_json.outputs.slug }}"

          if gh pr list --head "${BRANCH_NAME}" --state open | grep "${BRANCH_NAME}"; then
            echo "Pull request already exists, no need to create a new one."
          else
            gh pr create --title "$PR_TITLE" \
              --body "$PR_BODY" \
              --head "$BRANCH_NAME" \
              --base "main"
          fi
