name: Process JSON File Changes

on:
  push:
    branches:
      - main
    paths:
      - 'data/projects/*.json'

jobs:
  process_json:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Determine file status and content differences
        run: |
          # Determine file status and path
          FILE_CHANGE=$(git diff --name-status ${{ github.event.before }} ${{ github.event.after }} | grep data/projects/.*\.json)
          FILE_STATUS=$(echo $FILE_CHANGE | awk '{print $1}')
          FILE_PATH=$(echo $FILE_CHANGE | awk '{print $2}')

          if [ "$FILE_STATUS" == "A" ]; then
            echo "Action: Create new entry for $FILE_PATH"

            REPOS=$(jq '{repository: .links.repository}' "$FILE_PATH")

            RESPONSE=$(curl -s -X POST "${{ secrets.API_ENDPOINT }}" \
              -H "Content-Type: application/json" \
              -d "$REPOS")

            echo "Response from POST request: $RESPONSE"

          elif [ "$FILE_STATUS" == "M" ]; then
            # Fetch the old and new content of the file for comparison
            git show ${{ github.event.before }}:"$FILE_PATH" > old_file.json
            git show ${{ github.event.after }}:"$FILE_PATH" > new_file.json

            # Compare repositories array
            OLD_REPOS=$(jq -S '.links.repository | sort_by(.label, .url)' old_file.json)
            NEW_REPOS=$(jq -S '.links.repository | sort_by(.label, .url)' new_file.json)
            SYNC="false"

            if [ "$OLD_REPOS" != "$NEW_REPOS" ]; then
              SYNC="true"
              REPOS_TO_REMOVE=$(jq --argjson old "$OLD_REPOS" --argjson new "$NEW_REPOS" \
    '[$old[] | select(.label as $label | $new | index({label: $label}) | not)]')
              REPOS_TO_ADD=$(jq --argjson old "$OLD_REPOS" --argjson new "$NEW_REPOS" \
    '[$new[] | select(.label as $label | $old | index({label: $label}) | not)]')
            fi

            # Compare attributes object
            OLD_ATTRS=$(jq '.attributes' old_file.json | jq -S .)
            NEW_ATTRS=$(jq '.attributes' new_file.json | jq -S .)
            
            UPDATE="false"
            if [ "$OLD_ATTRS" != "$NEW_ATTRS" ]; then
              UPDATE="true"
            fi

            # Log actions based on conditions
            if [ "$SYNC" == "true" ]; then
              echo "Repositories to remove: $REPOS_TO_REMOVE"
              echo "Repositories to add: $REPOS_TO_ADD"
            fi
            if [ "$UPDATE" == "true" ]; then
              echo "Action: Update required due to change in attributes."
            fi
            if [ "$SYNC" == "false" ] && [ "$UPDATE" == "false" ]; then
              echo "No significant changes detected; no action taken."
            fi
          else
            echo "File deleted or other non-applicable change detected; no action taken."
          fi
