name: Process JSON File Changes

on:
  push:
    branches:
      - main
    paths:
      - 'data/projects/*.json'

jobs:
  process_json:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Determine file status and content differences
        run: |
          # Activate bash debugging to show commands and their arguments as they are executed
          set -euxo pipefail

          # Determine file status and path
          FILE_CHANGE=$(git diff --name-status ${{ github.event.before }} ${{ github.event.after }} | grep data/projects/*.json)
          echo "Detected file change: $FILE_CHANGE"
          FILE_STATUS=$(echo $FILE_CHANGE | awk '{print $1}')
          FILE_PATH=$(echo $FILE_CHANGE | awk '{print $2}')

          if [ "$FILE_STATUS" == "A" ]; then
            echo "Action: Create new entry for $FILE_PATH"
          elif [ "$FILE_STATUS" == "M" ]; then
            echo "File modified: $FILE_PATH"
            # Fetch the old and new content of the file for comparison
            git show ${{ github.event.before }}:"$FILE_PATH" > old_file.json
            git show ${{ github.event.after }}:"$FILE_PATH" > new_file.json

            echo "Old and new file content fetched for $FILE_PATH"

            # Compare repositories array
            OLD_REPOS=$(jq '.links.repositories | sort' old_file.json | jq -S .)
            NEW_REPOS=$(jq '.links.repositories | sort' new_file.json | jq -S .)
            echo "Old Repos: $OLD_REPOS"
            echo "New Repos: $NEW_REPOS"
            SYNC="false"
            if [ "$OLD_REPOS" != "$NEW_REPOS" ]; then
              SYNC="true"
            fi

            # Compare attributes object
            OLD_ATTRS=$(jq '.attributes' old_file.json | jq -S .)
            NEW_ATTRS=$(jq '.attributes' new_file.json | jq -S .)
            echo "Old Attributes: $OLD_ATTRS"
            echo "New Attributes: $NEW_ATTRS"
            UPDATE="false"
            if [ "$OLD_ATTRS" != "$NEW_ATTRS" ]; then
              UPDATE="true"
            fi

            # Log actions based on conditions
            if [ "$SYNC" == "true" ]; then
              echo "Action: Sync required due to change in repositories."
            fi
            if [ "$UPDATE" == "true" ]; then
              echo "Action: Update required due to change in attributes."
            fi
            if [ "$SYNC" == "false" ] && [ "$UPDATE" == "false" ]; then
              echo "No significant changes detected; no action taken."
            fi
          else
            echo "File deleted or other non-applicable change detected; no action taken."
          fi
