name: JSON Schema Validation

on:
  pull_request:
    paths:
      - '**/*.json' # Trigger the workflow for any JSON file changes in PRs

jobs:
  validate:
    name: Validate JSON files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install JSON Schema Validator and Formats
        run: |
          npm install -g ajv-cli ajv-formats
      
      - name: Validate JSON files
        run: |
          ajv -c ajv-formats validate -s schema.json -d '**/*.json' --strict=false
